Лабораторная 2
LizaSamoylova24/--PY101 pull request #1
Opened 2024-10-30 20:57 UTC by LizaSamoylova24

2024-10-31 15:00 UTC, rmushkin requested changes
Ошибка округления + мелочи по оформлению

2024-10-31 15:00 UTC, rmushkin commented on лабораторная 2  PyCharm/task1.py
> +print("Количество месяцев, которое можно протянуть без долгов:",months)
PEP8 :)

2024-10-31 15:00 UTC, rmushkin commented on лабораторная 2  PyCharm/task2.py
> +total_needed = round(total_needed)
Ловушка с `round`: 3 рублей не хватит, чтобы купить гвоздь за 3 рубля 25 копеек. Надо округлять в большую сторону.

2024-10-31 15:00 UTC, rmushkin commented on лабораторная 2  PyCharm/task2.py
> +print(f"Подушка безопасности, чтобы протянуть {months} месяцев без долгов:", total_needed )
PEP8!

2024-11-01 19:43 UTC, rmushkin requested changes
Ошибка с округлением исправлена, осталось только фоформление. [добавьте](https://docs.github.com/ru/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository), пожалуйста, меня в список коллабораторов, чтобы я мог закрыть пулл-реквест.

2024-11-01 19:43 UTC, rmushkin commented on лабораторная 2  PyCharm/task1.py
> +print("Количество месяцев, которое можно протянуть без долгов:",months)
Вы починили всё, кроме того, на что я показал 😅 
Я показывал на 12 строку, на пробел с запятой...

2024-11-01 19:51 UTC, LizaSamoylova24 commented
А как вас туда добавить?
--
Отправлено из  Mail для Android пятница, 01 ноября 2024г., 22:44 +03:00 от rmushkin  ***@***.*** :

>@rmushkin requested changes on this pull request.
>Ошибка с округлением исправлена, осталось только фоформление.  добавьте , пожалуйста, меня в список коллабораторов, чтобы я мог закрыть пулл-реквест.
>----------------------------------------------------------------------
>In  лабораторная 2  PyCharm/task1.py :
> @@ -0,0 +1,13 @@
>+money_capital = 20000  # Подушка безопасности
>+salary = 5000  # Ежемесячная зарплата
>+spend = 6000  # Траты за первый месяц
>+increase = 0.05  # Ежемесячный рост цен
>+
>+# TODO Посчитайте количество  месяцев, которое можно протянуть без долгов
>+months = 0  # Количество месяцев, которые можно протянуть без долгов
>+
>+while money_capital + salary >= spend:
>+    months += 1
>+    money_capital += salary - spend  # Обновляем подушку безопасности
>+    spend *= (1 + increase)           # Увеличиваем расходы на 5%
>+print("Количество месяцев, которое можно протянуть без долгов:",months)
>
>Вы починили всё, кроме того, на что я показал 😅
>Я показывал на 12 строку, на пробел с запятой...
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>

2024-11-01 20:13 UTC, rmushkin commented
Примерно так, спасибо :)

2024-11-01 20:13 UTC, merged